- hosts: all
  become: true

  handlers:
    - name: "restart nginx"
      service:
        name: nginx
        state: restarted                                                                           

  tasks:
    - name: "Download pacote jenkins"
      shell: wget -qO - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -

    - name: "Update apt"
      shell: "apt-get update"

    - name: "Instala java"
      shell: "apt install default-jdk -y"
